package com.projectbronze.wom.core;

import java.util.ArrayList;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import org.apache.logging.log4j.Logger;
import com.gt22.gt22core.interfaces.IMod;
import com.projectbronze.wom.material.Cloud;
import com.projectbronze.wom.proxy.CommonProxy;
import com.projectbronze.wom.registry.ItemRegistry;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(useMetadata = false, name = Core.name, modid = Core.modid, version = Core.version, dependencies = "required-after:Thaumcraft; required-after:TwilightForest; required-after:Botania; required-after:AWWayofTime; required-after:essentialcraft;")
public class Core implements IMod
{
	public static final String name = "World of Magic Mod";
	public static final String modid = "wommod";
	public static final int globalversion = 1; // We have rlease 1. Okay?
	public static final int minorversion = 0;
	public static final int gameversion = 1710;
	public static final int bugfixversion = 0;
	public static final String version = globalversion + "." + minorversion + "." + gameversion + "." + bugfixversion;
	private static final String clientproxy = "com.projectbronze.wom.proxy.ClientProxy";
	private static final String serverproxy = "com.projectbronze.wom.proxy.ServerProxy";
	public static CreativeTabs tabWoM = new CreativeTabs("tabWoM")
	{

		@Override
		public Item getTabIconItem()
		{
			return ItemRegistry.timeShard;
		}

	};

	@Override
	public CreativeTabs[] getCreativeTabs()
	{
		return new CreativeTabs[]
		{ tabWoM };
	}

	@Override
	public String getModid()
	{
		return modid;
	}

	public static Material cloud = new Cloud();
	@SidedProxy(clientSide = clientproxy, serverSide = serverproxy)
	public static CommonProxy proxy;

	@Instance(modid)
	public static Core instance = new Core();

	public static Logger log;

	@EventHandler
	public void preInit(FMLPreInitializationEvent e)
	{
		log = e.getModLog();
		proxy.preInit(e);
	}

	@EventHandler
	public void init(FMLInitializationEvent e)
	{
		proxy.init(e);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent e)
	{
		proxy.postInit(e);
	}

	private static void setupModMeta(ModMetadata m)
	{
		m.modId = "wommod";
		m.name = "Wom Mod";
		ArrayList<String> authors = new ArrayList<String>();
		authors.add("Project bronze team");
		m.authorList = authors;
		m.description = "Special mod for World of Magic modpack";
		m.autogenerated = false;
	}

}
